frontend/controllers/DocController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Documents;
use common\models\DocumentsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Users;
use \yii\web\Request;
use yii\web\UploadedFile;
use aryelds\sweetalert\SweetAlert;

/**
 * DocController implements the CRUD actions for Documents model.
 */
class DocController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'actions' => [''],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index','create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $valid_roles = [Users::ROLE_ADMIN, Users::ROLE_SUPERUSER];
                            return Users::roleInArray($valid_roles) && Users::isActive();
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Documents models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            
            return $this->redirect(["login"]);

        }
        else{

            if (Yii::$app->user->identity->role == Users::ROLE_USER){

                $user_id = Yii::$app->user->identity->id;

            }
            else{

                $user_id = null;            
            }

            $searchModel = new DocumentsSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $user_id);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
    }

    /**
     * Displays a single Documents model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Documents model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            
            return $this->redirect(["login"]);

        }
        
        else if (Yii::$app->user->identity->role == Users::ROLE_ADMIN || Yii::$app->user->identity->role == Users::ROLE_SUPERUSER){    

            $model = new Documents();
            $baseUrl =  (new Request)->getBaseUrl();
            $now = (new \yii\db\Query)->select(new \yii\db\Expression('NOW()'))->scalar();

            if ($model->load(Yii::$app->request->post())) {

                $model->publish_date = $now;


                $imagename = null;
                $val = 0;

                $user = Users::findOne($model->user_id);

                if (UploadedFile::getInstance($model, 'file_doc')) {

                    $imagename = $model->document_name.' - '.$user->fullname;
                    $model->file_doc = UploadedFile::getInstance($model, 'file_doc');
                    $model->document = 'docs/' . $imagename . '.' . $model->file_doc->extension;
                    $val = 1;
                }

                if ($val == 1) {
                    $model->save();  

                    if ($imagename) {
                        $model->file_doc->saveAs('docs/' . $imagename . '.' . $model->file_doc->extension);
                    }

                    SweetAlert::widget([
                        'options' => [
                            'title' => "Cargado Exitosamente",
                            // 'text' => "Gracias por verificar su cuenta, le informaremos cuando el proceso haya concluido.",
                            'type' => SweetAlert::TYPE_SUCCESS,
                            'animation' => 'slide-from-top',
                            'theme' => SweetAlert::THEME_GOOGLE,
                            'showCancelButton' => false,
                            'confirmButtonColor' => "#DD6B55",
                            'confirmButtonText' => "Gracias",
                            'closeOnConfirm' => false,
                            'closeOnCancel' => false
                        ],
                        'callbackJs' => new \yii\web\JsExpression(' function(isConfirm) {
                            if (isConfirm) { 
                                window.location="'.$baseUrl.'"
                            } 
                        }')
                    ]);

                    return $this->redirect(['doc/index']);

                    
                }
                else{
                    SweetAlert::widget([
                        'options' => [
                            'title' => "Debes subir el documento",
                            // 'text' => "Hay datos errados",
                            'type' => SweetAlert::TYPE_ERROR,
                            'animation' => 'slide-from-top',
                            'theme' => SweetAlert::THEME_GOOGLE
                        ]
                        ]);
                }

                return $this->redirect(['view', 'id' => $model->id_document]);
            }

            return $this->render('create', [
                'model' => $model,
            ]);
        }
             
        else{
            return $this->redirect(["login"]);

        }
        
    }

    /**
     * Updates an existing Documents model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_document]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Documents model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Documents model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Documents the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Documents::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/views/doc/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\Users;
use \yii\web\Request;

/* @var $this yii\web\View */
/* @var $model common\models\Documents */
/* @var $form yii\widgets\ActiveForm */

$baseUrl =  (new Request)->getBaseUrl();
?>

<div class="documents-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
    	<div class="col-md-6">
    		<?= $form->field($model, 'user_id')->dropDownList(
                ArrayHelper::map(Users::find()->all(), 'id_user', 'username', 'fullname'), ['prompt' => Yii::t('app', 'Select Pacient')])->label(Yii::t('app', 'Pacient'))?>
    	</div>
    	<div class="col-md-6">
    		<?= $form->field($model, 'document_name')->textInput(['maxlength' => true]) ?>		
    	</div>
    </div>

    <?= $form->field($model, 'file_doc', [
               'inputOptions' => ['class' => 'dropify', 'data-height'=> "300", 'data-default-file' => $baseUrl.'/id/'.$model->document, 'data-show-remove'=> 'false']])->fileInput()->label(Yii::t('app', 'Document')) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/doc/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\DocumentsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="documents-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_document') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'document_name') ?>

    <?= $form->field($model, 'document') ?>

    <?= $form->field($model, 'publish_date') ?> 

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/doc/create.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $model common\models\Documents */

$this->title = Yii::t('app', 'Load Document');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documents-create">

    <div class="row bg-title">
        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
            <h4 class="page-title"><?= Html::encode($this->title) ?></h4> 
        </div>
        <div class="col-lg-4 col-md-2 col-sm-2 col-xs-12"></div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <?=  Breadcrumbs::widget([
                  'homeLink' => [ 'label' => Yii::t('app', 'Dashboard'), 'url' => Yii::$app->homeUrl,],
                  'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
               ]) ?>
        </div>
    </div>

    <div class="white-box">
	    <?= $this->render('_form', [
	        'model' => $model,
	    ]) ?>
	</div>

</div>

frontend/views/doc/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use \yii\web\Request;
use yii\widgets\Breadcrumbs;
use common\models\Users;

/* @var $this yii\web\View */
/* @var $searchModel common\models\DocumentsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Documents');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="documents-index">

    <div class="row bg-title">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title"><?= Html::encode($this->title) ?></h4> 
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"></div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <?=  Breadcrumbs::widget([
                  'homeLink' => [ 'label' => Yii::t('app', 'Dashboard'), 'url' => Yii::$app->homeUrl,],
                  'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
               ]) ?>
        </div>
    </div>

    

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="white-box">

    <p>
        <?php if (Yii::$app->user->identity->role == Users::ROLE_ADMIN || Yii::$app->user->identity->role == Users::ROLE_SUPERUSER):
                echo Html::a(Yii::t('app', 'Load Document'), ['create'], ['class' => 'btn btn-success btn-rounded']);

                $botones = [
                    'class' => 'kartik\grid\ActionColumn', 
                    'template' => '{link}&nbsp;{edit}&nbsp;{delete}',
                    'buttons' => [
                        'link' => function($url, $model, $key) { 
                            $baseUrl = (new Request)->getBaseUrl();    // render your custom button
                            return Html::a('<i class="fa fa-cloud-download"></i>', $baseUrl.'/'.$model->document,
                                ['class' => 'btn-lg text-info', 'title' => Yii::t('app', 'Download'), 'target' =>'_blank']);
                        },
                        'edit' => function($url, $model, $key) {
                            return Html::a('<i class="fa fa-pencil-square-o"></i>', ['doc/update', 'id' => $model->id_document], [  'class' => 'btn-lg', 'title' => Yii::t('app', 'Edit'), 'style' => 'color:#81c700;']);
                        },

                        'delete' => function($url, $model, $key) {
                            return Html::a('<i class="fa  fa-trash-o"></i>', ['doc/delete', 'id' => $model->id_document], ['class' => 'btn-lg', 'title' => Yii::t('app', 'Delete'), 'id' => 'btn-del', 'style' => 'color:red;',
                                'data' => [
                                        'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                                        'method' => 'post',
                                    ],
                                ]);
                        },
                    ],
                    'contentOptions' =>['style'=>'text-align:center;', 'width' => '30%'],
                    'headerOptions' =>['style'=>'text-align:center;', 'width' => '30%'],
                ];
            else:
                $botones = [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{link}',
                    'header' => Yii::t('app', 'Download'),
                    'buttons' => [
                        'link' => function($url, $model, $key) { 
                            $baseUrl = (new Request)->getBaseUrl();    // render your custom button
                            return Html::a(Yii::t('app', 'Download'), $baseUrl.'/'.$model->document,
                                ['class' => 'btn btn-danger btn-block btn-download btn-rounded', 'target' =>'_blank']);
                        }
                    ],
                    'contentOptions' =>['style'=>'text-align:center;', 'width' => '15%'],
                    'headerOptions' =>['style'=>'text-align:center;', 'width' => '15%'],
                ];
            endif;
        ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            // ['class' => 'yii\grid\SerialColumn'],

            // 'id_document',
            
            [
                'attribute' => 'username',
                'value' => 'user.username',  
                'label' => Yii::t('app', 'Username'), 
                'contentOptions' =>['style'=>'text-align:center;', 'width' => '10%'],
                'headerOptions' =>['style'=>'text-align:center;', 'width' => '10%'], 
            ],
            [
                'attribute' => 'fullname',
                'value' => 'user.fullname', 
                'label' => Yii::t('app', 'Full Name'), 
                'contentOptions' =>['style'=>'text-align:left;', 'width' => '20%'],
                'headerOptions' =>['style'=>'text-align:left;', 'width' => '20%'],  
            ],
           
            [
                'attribute' => 'document_name',
                'label' => Yii::t('app', 'Document Name'),
                'contentOptions' =>['style'=>'text-align:left;', 'width' => '30%'],
                'headerOptions' =>['style'=>'text-align:left;', 'width' => '30%'],
            ],
            [
                'attribute' => 'publish_date',
                'label' => Yii::t('app', 'Publish Date'),
                'contentOptions' =>['style'=>'text-align:center;', 'width' => '15%'],
                'headerOptions' =>['style'=>'text-align:center;', 'width' => '15%'],
            ],
            $botones,
        ],
    ]); ?>

</div>


</div>

frontend/views/doc/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Documents */

$this->title = Yii::t('app', 'Update Documents: {name}', [
    'name' => $model->id_document,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_document, 'url' => ['view', 'id' => $model->id_document]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="documents-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/doc/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Documents */

$this->title = $model->id_document;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Documents'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="documents-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id_document], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id_document], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id_document',
            'user_id',
            'document_name',
            'document',
            'publish_date',
        ],
    ]) ?>

</div>